# Generated by Django 5.2 on 2025-10-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Номи категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Сурат (категория)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорияҳо',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номи маҳсулот')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тавсиф')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нархи харид')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нархи фурӯш')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Сурат')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Маҳсулот',
                'verbose_name_plural': 'Маҳсулотҳо',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ном')),
                ('last_name', models.CharField(max_length=80, verbose_name='Насаб')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(max_length=250, verbose_name='Суроға')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Миқдор')),
                ('payment_method', models.CharField(choices=[('cash', 'Нақд'), ('card', 'Корти бонкӣ'), ('transfer', 'Пулгузаронӣ (QR/аппа)')], default='cash', max_length=30, verbose_name='Тарзи пардохт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи фармоиш')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказҳо',
            },
        ),
    ]
