# Generated by Django 5.2 on 2025-10-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Санаи воридот')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шарҳ')),
            ],
            options={
                'verbose_name': 'Воридоти нав',
                'verbose_name_plural': 'Воридотҳои нав',
            },
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Миқдор')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нархи харид (як дона)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.incomingbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Маҳсулоти воридшуда',
                'verbose_name_plural': 'Маҳсулотҳои воридшуда',
            },
        ),
    ]
