# Generated by Django 5.2 on 2025-10-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_incomingbatch_incomingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingitem',
            options={},
        ),
        migrations.AlterField(
            model_name='incomingitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Нархи харид (як дона)'),
        ),
        migrations.AlterField(
            model_name='incomingitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Миқдор'),
        ),
        migrations.CreateModel(
            name='DebtorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Номи аввал')),
                ('last_name', models.CharField(max_length=100, verbose_name='Номи охир')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Суроға')),
                ('quantity', models.PositiveIntegerField(verbose_name='Миқдор')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Маблағи умумӣ')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Пардохт шуд/нашуд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи фармоиш')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Клиент карздор',
                'verbose_name_plural': 'Клиентҳои карздор',
            },
        ),
    ]
