# Generated by Django 5.2 on 2025-10-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_incomingitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtorclient',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='debtorclient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='debtorclient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='debtorclient',
            name='total_price',
        ),
        migrations.CreateModel(
            name='DebtorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Миқдор')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Маблағи умумӣ')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Пардохт шуд/нашуд')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.debtorclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Маҳсулоти карздор',
                'verbose_name_plural': 'Маҳсулотҳои карздор',
            },
        ),
    ]
