"""
Django settings for bunyod_shop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=6yo@@ob=l_)m&n)h6rx^5rp=5=8)90)i2ner1p+_ldkha=(vd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
INSTALLED_APPS = [
    'jazzmin',                # <— илова шуд
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

# settings.py
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
    ('tg', 'Tajik'),  # забони тоҷикӣ
]

LANGUAGE_CODE = 'tg'  # бояд яке аз LANGUAGES бошад

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Инро фаромӯш накунед
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


LOCALE_PATHS = [BASE_DIR / 'locale']  # 🔹 ҷойи файлҳои тарҷума

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



ROOT_URLCONF = 'bunyod_shop.urls'

WSGI_APPLICATION = 'bunyod_shop.wsgi.application'

# settings.py
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # агар шаблонҳои иловагӣ доред
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "МАГОЗАИ БУНЁД",
    "site_header": "Админ панел — Магозаи Бунёд",
    "site_brand": "МАГОЗАИ БУНЁД",
    "site_logo": "store/img/logo.png",  # логотипи ту (агар дар static бошад)
    "login_logo": "store/img/logo.png",
    "welcome_sign": "Салом, Бунёд!",
    "copyright": "© 2025 Магозаи Бунёд",

    "show_ui_builder": False,
    "related_modal_active": True,

    # Палитра — аз логотип
    "theme": "cyborg",
    "custom_css": None,
    "custom_js": None,

    # Рангҳо (аз логотип)
    "topmenu_links": [
        {"name": "Сахифаи асоси", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    "icons": {
        "store.Product": "fas fa-cube",
        "store.Category": "fas fa-list",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    "usermenu_links": [
        {"model": "auth.user"},
        {"name": "Баромад", "url": "/admin/logout/"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    # Рангҳо (ҳамин тавр мисли логотип)
    "custom_links": {
        "store": [{
            "name": "Cахифаи асосои",
            "url": "/",
            "icon": "fas fa-home",
            "permissions": ["store.view_product"]
        }]
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "navbar": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-green",
    "accent": "accent-green",
    "button_classes": {
        "primary": "btn btn-success",
        "secondary": "btn btn-outline-light",
    },
    "dark_mode_theme": "slate",
}
